#! /usr/bin/env bash

SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TARGET_DIR="$(pwd)"

NAME="$(basename $TARGET_DIR)"
DISPLAY_NAME="$NAME"

echo $TARGET_DIR_NAME
copier -d name="$NAME" -d display_name="$DISPLAY_NAME" "${SOURCE_DIR}" .
